openapi: 3.2.0
info:
  title: Unito Embed Server API
  version: 0.1.4
  description: 'Welcome to Unito Embed API documentation


    In order to be able to use that api, Unito must first create an embed entity for you and give you its api key.'
servers:
- url: http://localhost:9080
  description: local
- url: https://staging-api.unito.io
  description: staging
- url: https://api.unito.io
  description: production
  variables:
    embedId:
      default: wrike
security:
- ApiKeyAuth: []
tags:
- name: Server
paths:
  /health/ready:
    get:
      summary: Whether the service is ready to serve requests
      x-eov-operation-id: ready
      x-eov-operation-handler: health
      tags:
      - Server
      security: []
      responses:
        '200':
          description: The service is ready to receive requests
        '503':
          description: The service is NOT ready to receive requests
      operationId: getHealthReady
      x-operation-id-source: derived
  /health/alive:
    get:
      summary: Whether the service is responsive
      x-eov-operation-id: alive
      x-eov-operation-handler: health
      tags:
      - Server
      security: []
      responses:
        '200':
          description: The service is alive
      operationId: getHealthAlive
      x-operation-id-source: derived
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
